### PR TITLE
Updated project to use Django 1.6

### PR DESCRIPTION
**Pull request by alej0varas**

### CODE REVIEW

**Comment by santiagomalter** [comment]
Hi Alejandro,

So no changes in the settings for 1.6? django-skel 1.5 can be used "as is" for django 1.6?

Santiago

**Comment by alej0varas** [comment]
Hi Santiago

I'll check but at least I've tried creating a project and running `manage.py check` and no warning/error was raised.
Anyway more works needs to be done because I've seen some dependencies like debug toolbar failing.

**Comment by rdegges** [comment]
Hm, I'll merge this if someone wants to include the other patches necessary to make 1.6 work smoothly. I'm really tied down with my company at the moment, and don't have the time to jump into it right away.

If anyone submits some more to the PR, I'd be more than happy to merge!

You guys are the best.

<3

-Randall

**Comment by alej0varas** [comment]
Just noted that a lot more work needs to be done like testing all the requirements! I'll move one of my projects to 1.6 and start contributing from there.

**Comment by Miserlou** [comment]
@alej0varas  - what's the word on this? I'm interested in using django-16-skel - is yours in a good state?

**Comment by alej0varas** [comment]
@Miserlou Yes, I'm using it without any issue. But still need to test all the dependencies against Django 1.6.

**Comment by wadewilliams** [comment]
:rooster: 1.7

**Pull request closed without merging**
